travis:
  secure:
    BINSTAR_TOKEN: Mlq2bCumiSrtCMflZlVm9LJglaEKA+EfB4j8oO9629okBlvbk++eKcOeczcEwdUUIoTGMqLPwEUmvMnML3QMnpBSqLyBeQPnsqYIidGh66KbOyKQpPMoS08wyzBdZc14+R/tbG6t2SqBMeBVis04XpZ83NIBQ5YWvToqFLMxHbTttp65UpK+b0EunPytTSl+Tk8rSt8OfKloMtxtP6H9BVjc8nKA2pgTuLW12y7gSG71N2cwyf40RS7yG7OMD9YTF+h7frAeD3vN1E08w7KPt3ZyE0U+REu+wzlRj0qkGe8YfJohwW9Wsjg9+KtLFHwT2cNxgx4xkee3NMo7oA2FOxokyacCREznoPFxzlHBjI/Q2CeNPFU1/eiXsMaikU/DBoX/zati+eKMuC+/STGWaswEdzteRqWVhFWs7ppNsdL4+k2zfVm5NWpj5CjQ68iy+ksd0c4/b+YE7tVGRFl9/bxmwAfPV9KG1Bp7cLK3LdLJHIfUVfjnruowhwMlsJHMVotWE7vZMZQGsISu91Oy9nI4EVy5HKRplcepWe0FnpHS2hPOqN0fsEjr29UZBZHl+vH3JT/WA3iLVeZuWZ1lg+8alIN3iWosSZVV3pID4z9x/YSFqUYmjVUGfB05Ai4JlpIwA5IwpTxu9rpfuegqr+ah40L33snkej37lnW+0D0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
